/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class A {
    static a: int[] = [1, 2, 3, 4, 5];
    static b: int[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    static c = 0;
    static run1() {
        arktest.assertEQ(A.b[A.a[A.c]], 2);
        A.b[A.a[++A.c]] += 1;
        arktest.assertEQ(A.b[A.a[A.c]], 4);
    }
    static run2() {
        let array1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
        arktest.assertEQ(A.b[array1[A.c]], 2);
        A.b[array1[++A.c]] += 1;
        arktest.assertEQ(A.b[array1[A.c]], 3);
    }
    static run3() {
        let array1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
        arktest.assertEQ(A.b[A.a[array1[A.c]]], 4);
        A.b[A.a[array1[++A.c]]] += 1;
        arktest.assertEQ(A.b[A.a[array1[A.c]]], 5);
    }
}

function main() {
    A.run1();
    A.run2();
    A.run3();
}

