/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


function main() {
    let x1 = 2;
    let y1 = 3;
    let z1: number = x1 ** y1;
    arktest.assertDoubleEQ(z1, 8, 0.00001);
    let z2: number = 3 ** 3;
    arktest.assertDoubleEQ(z2, 27, 0.00001);
    let z3 = 4.0 ** 3;
    arktest.assertDoubleEQ(z3, 64, 0.00001);
    let x4 = 5;
    let y4 = 3;
    arktest.assertDoubleEQ(x4 ** y4, 125, 0.00001);
}
