/**
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at*
 *
 * http://www.apache.org/licenses/LICENSE-2.0*
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let a: int | double = 1;

function test(): double {
    let a1: int = 1;
    let a2: int = 1;
    let a3: int = 1;
    let a4: int = 1;
    let a5: int = 1;
    let a6: int = 1;
    let a7: int = 1;
    let a8: int = 1;
    let a9: int = 1;
    let a10: int = 1;
    let a11: int = 1;
    let a12: int = 1;
    let a13: int = 1;
    let a14: int = 1;
    let a15: int = 1;
    let a16: int = 1;
    return a.toDouble();
}

function main() {
    arktest.assertEQ(test(), 1.0);
}