/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class unary_operations  {
    private a: int = 3;
    private pref1: int;
    private pref2: int;
    private pref3: int;
    private pref4: int;
    private pref5: int;
    private b: boolean;
    private pref6: boolean;
    private post1: int;
    private post2: int;
    constructor() {
        this.pref1 = +this.a;
        this.pref2 = -this.a;
        this.pref3 = ++this.a;
        this.pref4 = --this.a;
        this.pref5 = ~this.a;
        this.b = false;
        this.pref6 = !this.b;
        this.post1 = this.a++;
        this.post2 = this.a--;
    }
}
