/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Class1 } from 'file_1.ets';
import type { Class1 as Class_1 } from 'file_1.ets';
import type { Interface1 } from 'file_1.ets';
import type { Interface1 as Interface_1 } from 'file_1.ets';

export class Class2 {
  constructor() {}
}

export interface Interface2 {
}

function f1(value: Class1): void {
}

function f2(value: Class_1): void {
}
