/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
import {
  a,
  a1,
  a2,a3,a4,a5,
  a6,a7,
  b,
  c,
  d,
  ET,
  e,
  e2,
  e3,
  X,
  f,
  g,
  gt,
  g2,
  g3,
  h,
  i,
  j,
  k,
  K1,
  K2,
  l,l1,
  l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13,l14,l15,
  m,
  IndexedAccessType,
  IndexedAliasType,
  n,
  ConditionalType,
  o,
  MappedType,
  TXY,
  p,
  TemplateType,
  q,
  QT,
  qv,
  r,
  s,
  t,
  u,
  v,
  w,
  x,
  y,
  z,
  aa,
  ab,
  ac,
  NS,
  MD
} from "./ignore_files/unique_types4";

  
// any
a3; 
a4("test"); 
a5("test"); 
console.info('a6' + a6);

// mixing enum
f; 

// call signature
g2(); 

// keyof
let k2: K2;
k;

// typeof 
l2;

// complex 
let tl3: l3;

let tl5: l5;
l13({x:1,y:"2"});
new l14();
let ll15: l15;

// utils
qv;

// namespace
let ii1: NS.ns_interface; 
let ii2: NS.X; 

// module
let ii3: MD.md_intereface; 
let ii4: MD.X; 
