/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 






let Wiki = ESValue.load('./interop_import_js_js').getProperty('Wiki');
let Doge = ESValue.load('./interop_import_js_js').getProperty('Dog');
let tjs = ESValue.load('./interop_import_js_js').getProperty('tjs');
let myAaa = ESValue.load('./interop_import_js_js').getProperty('aaa');
let ClassA = ESValue.load('./interop_import_js_js').getProperty('ClassA');
let Dog = ESValue.load('./interop_import_js_js').getProperty('Dog');
let myAaa = ESValue.load('./interop_import_js_js').getProperty('aaa');
let CPreview = ESValue.load('./jsfiles/preview_import_js').getProperty('CPreview');
let bar = ESValue.load('./jsfiles/preview_import_js').getProperty('bar');
let foo = ESValue.load('./jsfiles/preview_import_js').getProperty('foo');
let fjs = ESValue.load('../main/js_lib').getProperty('fjs');
let Cjs = ESValue.load('../main/js_lib').getProperty('Cjs');
