/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let fn = (
    str1: String,
    str2: String,
    str3: String,
    str4: String,
    str5: String,
    str6: String,
    str7: String,
    str8: String,
    str9: String,
    str10: String,
    str11: String,
    str12: String,
    str13: String,
    str14: String,
    str15: String,
    str16: String,
    str17: String,
    ...restStr: String[]
): void => { };

function main(): void {
   fn("hello", "world", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!");
}


/* @@? 38:4 Error Semantic error ESE0124: Expected 17 arguments, got 15. */
/* @@? 38:4 Error Semantic error ESE0127: No matching call signature for ("hello", "world", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!", "!") */