/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*---
    tags: [compile-only, negative]
---*/

async WeakMap => ...delete const { Intl } = [ { opt } = [({} ? 4 : Array[-=])];
, ... || new ({.: 0}[])(,{: 88}["-1"]), ...opt, (7 ?  : null)][true[( ? 5 : {}.arity.E)]];
 >>>= sub(await delete await ArrayBuffer ^= await delete )<missing '
'> __a:be
}