/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { m } from 'module'

import { a, b } from 'module1'
import { c } from 'module2'

import {worker} from '@kit.ArkTS';   // (arkts-no-lazy-import)

import {harTest} from "har1" // (arkts-no-lazy-import)

import {add} from "hsp1" // (arkts-no-lazy-import)

/* test */ import {WorkerEventListener} from '@kit.ArkTS'; // (arkts-no-lazy-import)

import /* test */ {WorkerEventTarget} from '@kit.ArkTS'; // (arkts-no-lazy-import)

/* test */ import /* test */  /* test */ {WorkerOptions} /* test */  from '@kit.ArkTS'; // (arkts-no-lazy-import)

import {worker as wk} from '@kit.ArkTS'; // (arkts-no-lazy-import)

/* test */ import /* test */
// (arkts-no-lazy-import)
/* test */ {worker as ttt} /* test */  from '@kit.ArkTS';