/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class Pair3 {
  a: number;
  b: number;
  constructor(values: [number, number]) {
    [this.a, this.b] = values;
  }
}

function main() {
  let p: Pair3 = new Pair3([10, 20]);
  arktest.assertEQ(p.a, 10);
  arktest.assertEQ(p.b, 20);
}
