/**
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cstdint>
#include <fstream>
#include <sstream>
#include <gtest/gtest.h>
#include "nlohmann/json.hpp"
#include "gluegen.h"
#include "gluel.h"

using ark::es2panda::gluegen::GlueConfig;
using ark::es2panda::gluegen::Gluegen;
using ark::es2panda::gluegen::GluegenOptions;
using ark::es2panda::gluegen::SymbolKind;

namespace {

// Repo-wide fixture generated by ets2panda's own CMakeLists.txt (`gen_arktsconfig(...)`) for use
// by gtests placed under `bin-gtests/` -- see arkcompiler/ets_frontend/ets2panda/CMakeLists.txt.
// BUILD_FOLDER (the static_core build root) is injected as a compile definition for every target
// in this build (see runtime_core/static_core/CMakeLists.txt's `add_definitions(-DBUILD_FOLDER=...)`),
// the same mechanism `test::utils::PandaExecutablePathGetter` relies on for the es2panda binary path.
std::string ArktsConfigPath()
{
#ifdef BUILD_FOLDER
    return std::string(BUILD_FOLDER) + "/bin-gtests/arktsconfig.json";
#else
    ADD_FAILURE() << "BUILD_FOLDER not set";
    return {};
#endif
}

// RAII helper creating a fresh, empty temp directory for a single test and removing it (and
// everything under it) again on destruction, mirroring utils_test.cpp's manual-cleanup-via-
// std::error_code pattern for temp-file-based tests.
class ScopedTempDir {
public:
    explicit ScopedTempDir(const std::string &prefix)
    {
        path_ = fs::temp_directory_path() / (prefix + "_" + std::to_string(reinterpret_cast<std::uintptr_t>(this)));
        fs::create_directories(path_);
    }

    ~ScopedTempDir()
    {
        std::error_code ec;
        fs::remove_all(path_, ec);
    }

    ScopedTempDir(const ScopedTempDir &) = delete;
    ScopedTempDir &operator=(const ScopedTempDir &) = delete;

    const fs::path &Path() const
    {
        return path_;
    }

private:
    fs::path path_;
};

std::string ReadFile(const fs::path &path)
{
    std::ifstream in(path, std::ios::binary);
    std::ostringstream contentStream;
    contentStream << in.rdbuf();
    return contentStream.str();
}

class GluegenRunTest : public ::testing::Test {
protected:
    void SetUp() override
    {
        arktsconfigPath_ = ArktsConfigPath();
        if (!fs::exists(arktsconfigPath_)) {
            std::string skipMsg = "gtest arktsconfig.json fixture not found at " + arktsconfigPath_ +
                                  " -- build the repo's gtests first so ets2panda's CMakeLists.txt "
                                  "generates it.";
            GTEST_SKIP() << skipMsg;
        }
    }

    std::string arktsconfigPath_;
};

TEST_F(GluegenRunTest, RunProducesExpectedSymbolsForValidSource)
{
    ScopedTempDir dir("gluegen_run_valid");
    const auto sourceFile = dir.Path() / "a.ets";
    {
        std::ofstream out(sourceFile);
        out << "export class Foo {}\n";
        out << "export function bar(): int {\n";
        out << "  return 1;\n";
        out << "}\n";
    }
    const auto outputPath = dir.Path() / "output.json";

    GluegenOptions options;
    options.sourceFiles = {sourceFile.string()};
    options.arktsconfigPath = arktsconfigPath_;
    options.outputPath = outputPath.string();
    options.cacheDir.clear();  // no incremental caching for this test

    Gluegen gluegen(options);
    auto result = gluegen.Run();
    ASSERT_TRUE(result) << result.Error();
    ASSERT_TRUE(fs::exists(outputPath));

    ark::es2panda::gluegen::SymbolNodeManager manager;
    auto config = GlueConfig::deserialize(ReadFile(outputPath), manager);
    EXPECT_EQ(config.status, "success");
    ASSERT_EQ(config.files.size(), 1U);
    const auto &fileConfig = config.files.begin()->second;

    ASSERT_EQ(fileConfig.root.count("Foo"), 1U);
    EXPECT_EQ(fileConfig.root.at("Foo")->kind, SymbolKind::CLASS);
    ASSERT_EQ(fileConfig.root.count("bar"), 1U);
    EXPECT_EQ(fileConfig.root.at("bar")->kind, SymbolKind::FUNCTION);
}

TEST_F(GluegenRunTest, RunWritesSyntaxErrorStatusForInvalidSource)
{
    ScopedTempDir dir("gluegen_run_syntax_error");
    const auto sourceFile = dir.Path() / "bad.ets";
    {
        std::ofstream out(sourceFile);
        // Missing a class name: not valid ArkTS syntax.
        out << "export class {}\n";
    }
    const auto outputPath = dir.Path() / "output.json";
    const auto reportPath = dir.Path() / "report.json";

    GluegenOptions options;
    options.sourceFiles = {sourceFile.string()};
    options.arktsconfigPath = arktsconfigPath_;
    options.outputPath = outputPath.string();
    options.reportPath = reportPath.string();
    options.cacheDir.clear();

    ark::es2panda::gluegen::Gluegen gluegen(options);
    auto result = gluegen.Run();
    // A syntax error is a normal, terminal outcome for Run() -- not a tool failure.
    ASSERT_TRUE(result) << (result ? std::string() : result.Error());
    ASSERT_TRUE(fs::exists(outputPath));

    auto j = nlohmann::json::parse(ReadFile(outputPath));
    ASSERT_TRUE(j.contains("status"));
    EXPECT_EQ(j.at("status").get<std::string>(), "syntax-error");

    // The negative outcome should also be visible via DiagnosticEngine's own structured report
    // (written to --report-path), not just the ad hoc {"status": ...} file -- assert against the
    // recorded code/severity there rather than any particular wording.
    ASSERT_TRUE(fs::exists(reportPath));
    auto report = nlohmann::json::parse(ReadFile(reportPath));
    ASSERT_TRUE(report.contains("diagnostics"));
    const auto &warnings = report.at("diagnostics").at("warnings");
    ASSERT_FALSE(warnings.empty());
    EXPECT_EQ(warnings.at(0).at("code").get<std::string>(),
              std::to_string(static_cast<uint32_t>(ark::es2panda::gluegen::DiagnosticCode::SOURCE_PARSE_FAILED)));
    EXPECT_TRUE(report.at("diagnostics").at("errors").empty());
}

TEST_F(GluegenRunTest, RunReportsDiagnosticForMissingArktsconfig)
{
    ScopedTempDir dir("gluegen_run_missing_arktsconfig");
    const auto sourceFile = dir.Path() / "a.ets";
    {
        std::ofstream out(sourceFile);
        out << "export class Foo {}\n";
    }
    const auto outputPath = dir.Path() / "output.json";
    const auto reportPath = dir.Path() / "report.json";

    GluegenOptions options;
    options.sourceFiles = {sourceFile.string()};
    options.arktsconfigPath = (dir.Path() / "no-such-arktsconfig.json").string();
    options.outputPath = outputPath.string();
    options.reportPath = reportPath.string();
    options.cacheDir.clear();

    ark::es2panda::gluegen::Gluegen gluegen(options);
    // Run() now calls Initialize() internally; a missing arktsconfig causes Initialize() to fail
    // inside RunImpl(), and WriteDiagnosticsReport() still writes the structured report so
    // DiagnosticEngine's records are observable even on failure paths.
    auto result = gluegen.Run();
    ASSERT_FALSE(result);
    EXPECT_NE(result.Error().find("Arktsconfig"), std::string::npos) << result.Error();
    EXPECT_FALSE(fs::exists(outputPath));

    // Even on a hard failure, WriteDiagnosticsReport() still runs (see Gluegen::Run()), so the
    // ERROR diagnostic is observable via the structured report.
    ASSERT_TRUE(fs::exists(reportPath));
    auto report = nlohmann::json::parse(ReadFile(reportPath));
    const auto &errors = report.at("diagnostics").at("errors");
    ASSERT_FALSE(errors.empty());
    EXPECT_EQ(errors.at(0).at("code").get<std::string>(),
              std::to_string(static_cast<uint32_t>(ark::es2panda::gluegen::DiagnosticCode::INVALID_CONFIG)));
}

TEST_F(GluegenRunTest, RunWithCacheDirPopulatesDiskCacheAndSecondRunSucceeds)
{
    ScopedTempDir dir("gluegen_run_cache");
    const auto sourceFile = dir.Path() / "a.ets";
    {
        std::ofstream out(sourceFile);
        out << "export class Foo {}\n";
    }
    const auto outputPath = dir.Path() / "output.json";
    const auto cacheDir = dir.Path() / "cache";

    GluegenOptions options;
    options.sourceFiles = {sourceFile.string()};
    options.arktsconfigPath = arktsconfigPath_;
    options.outputPath = outputPath.string();
    options.cacheDir = cacheDir.string();

    {
        Gluegen gluegen(options);
        auto result = gluegen.Run();
        ASSERT_TRUE(result) << result.Error();
    }
    EXPECT_TRUE(fs::exists(cacheDir / "manifest.json"));
    EXPECT_TRUE(fs::exists(cacheDir / "intermediates"));

    // Second run against the now-populated cache should still succeed (whether or not it
    // actually reuses the cache internally is not observable from the public API, but it must
    // not error out or corrupt the output).
    GluegenOptions secondOptions = options;
    Gluegen secondGluegen(secondOptions);
    auto secondResult = secondGluegen.Run();
    ASSERT_TRUE(secondResult) << secondResult.Error();

    ark::es2panda::gluegen::SymbolNodeManager manager;
    auto config = GlueConfig::deserialize(ReadFile(outputPath), manager);
    EXPECT_EQ(config.status, "success");
    ASSERT_EQ(config.files.size(), 1U);
    EXPECT_EQ(config.files.begin()->second.root.count("Foo"), 1U);
}

TEST_F(GluegenRunTest, RunSucceedsForValidSource)
{
    ScopedTempDir dir("gluegen_run_valid_minimal");
    const auto sourceFile = dir.Path() / "a.ets";
    {
        std::ofstream out(sourceFile);
        out << "export class Foo {}\n";
    }
    const auto outputPath = dir.Path() / "output.json";

    GluegenOptions options;
    options.sourceFiles = {sourceFile.string()};
    options.arktsconfigPath = arktsconfigPath_;
    options.outputPath = outputPath.string();
    options.cacheDir.clear();

    Gluegen gluegen(options);
    auto result = gluegen.Run();
    ASSERT_TRUE(result) << result.Error();
    EXPECT_TRUE(fs::exists(outputPath));
}

TEST_F(GluegenRunTest, RunFailsWhenNoSourceFilesProvided)
{
    ScopedTempDir dir("gluegen_run_no_sources");
    const auto outputPath = dir.Path() / "output.json";

    GluegenOptions options;
    options.sourceFiles.clear();
    options.arktsconfigPath = arktsconfigPath_;
    options.outputPath = outputPath.string();
    options.cacheDir.clear();

    Gluegen gluegen(options);
    auto result = gluegen.Run();
    ASSERT_FALSE(result);
    EXPECT_NE(result.Error().find("source file"), std::string::npos) << result.Error();
}

TEST_F(GluegenRunTest, RunFailsWhenSourceFileDoesNotExist)
{
    ScopedTempDir dir("gluegen_run_missing_source");
    const auto outputPath = dir.Path() / "output.json";

    GluegenOptions options;
    options.sourceFiles = {(dir.Path() / "no-such-file.ets").string()};
    options.arktsconfigPath = arktsconfigPath_;
    options.outputPath = outputPath.string();
    options.cacheDir.clear();

    Gluegen gluegen(options);
    auto result = gluegen.Run();
    ASSERT_FALSE(result);
    EXPECT_NE(result.Error().find("Source file does not exist"), std::string::npos) << result.Error();
}

}  // namespace
