/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let arr: readonly int[] = [1];

arr.extendTo(2, 0);
arr.shrinkTo(2);
arr.sort();
arr.shift();
arr.pop();
arr.push(2, 3);
arr.splice(0,1,2,3);
arr.unshift(-1);
arr.copyWithin(0,0,0);
arr.fill(3);
arr.toSpliced();
arr.reverse();
arr.with(0, 5);

/* @@? 18:5 Error Semantic error ESE0087: Property 'extendTo' does not exist on type 'ReadonlyArray' */
/* @@? 19:5 Error Semantic error ESE0087: Property 'shrinkTo' does not exist on type 'ReadonlyArray' */
/* @@? 20:5 Error Semantic error ESE0087: Property 'sort' does not exist on type 'ReadonlyArray' */
/* @@? 21:5 Error Semantic error ESE0087: Property 'shift' does not exist on type 'ReadonlyArray' */
/* @@? 22:5 Error Semantic error ESE0087: Property 'pop' does not exist on type 'ReadonlyArray' */
/* @@? 23:5 Error Semantic error ESE0087: Property 'push' does not exist on type 'ReadonlyArray' */
/* @@? 24:5 Error Semantic error ESE0087: Property 'splice' does not exist on type 'ReadonlyArray' */
/* @@? 25:5 Error Semantic error ESE0087: Property 'unshift' does not exist on type 'ReadonlyArray' */
/* @@? 26:5 Error Semantic error ESE0087: Property 'copyWithin' does not exist on type 'ReadonlyArray' */
/* @@? 27:5 Error Semantic error ESE0087: Property 'fill' does not exist on type 'ReadonlyArray' */
/* @@? 28:5 Error Semantic error ESE0087: Property 'toSpliced' does not exist on type 'ReadonlyArray' */
/* @@? 29:5 Error Semantic error ESE0087: Property 'reverse' does not exist on type 'ReadonlyArray' */
/* @@? 30:5 Error Semantic error ESE0087: Property 'with' does not exist on type 'ReadonlyArray' */
