/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

try {
    let x = 77
} catch(a)
}

try
    let x = 55
} finally (x)
}


while {}

while x > 0 {}

let a = let x = 77.0;

function f(x: number, ... args: FixedArray<number>) {
    "use strict"
}

function foo() {
    private @annotate
    let a: number = 10;
}

for (let i = 1 in [0, 1, 2]) {}


/* @@? 19:1 Error Syntax error ESY0230: Expected '{', got '}'. */
/* @@? 22:5 Error Syntax error ESY0230: Expected '{', got 'let'. */
/* @@? 23:11 Error Syntax error ESY0230: Expected '{', got '('. */
/* @@? 23:11 Error Semantic error ESE0143: Unresolved reference x */
/* @@? 27:7 Error Syntax error ESY0230: Expected '(', got '{'. */
/* @@? 27:7 Error Semantic error ESE0062: need to specify target type for class composite */
/* @@? 29:1 Error Syntax error ESY0230: Expected ')', got 'while'. */
/* @@? 29:7 Error Syntax error ESY0230: Expected '(', got 'identification literal'. */
/* @@? 29:13 Error Syntax error ESY0230: Expected ')', got '{'. */
/* @@? 31:9 Error Syntax error ESY0227: Unexpected token 'let'. */
/* @@? 31:13 Error Syntax error ESY0227: Unexpected token 'x'. */
/* @@? 34:5 Error Syntax error ESY0199: Illegal 'use strict' directive in function with non-simple parameter list. */
/* @@? 38:5 Error Syntax error ESY0210: Annotation declaration can not have access modifier. */
/* @@? 38:5 Error Syntax error ESY0227: Unexpected token 'private'. */
/* @@? 38:13 Error Syntax error ESY0227: Unexpected token '@'. */
/* @@? 38:14 Error Semantic error ESE0371: Cannot find type 'annotate'. */
/* @@? 42:16 Error Syntax error ESY105822: 'in' operator is not supported. Use 'instanceof' operator to check whether an object is the instance of a class that contains the necessary class member. */
/* @@? 42:28 Error Syntax error ESY0230: Expected ';', got ')'. */
/* @@? 42:28 Error Syntax error ESY0167: Invalid left-hand side in 'For[In/Of]Statement'. */