/*
 * Copyright (c) 2023-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function main(): void {
    let apple : Byte = 0;
    let banana : Short = 1;
    let cherry : Int = 2;
    let date : Long = Double.toLong(3.0);
    let elderberry : Float = Double.toFloat(4.0);
    let fig : Float = Double.toFloat(4.0);
    let grape : Double = -5.0;
    let honeydewmelon : Double = 5.0;
    let indian_fig = Int.toChar(65);


    let raspberry : Short = Double.toShort(1.0);
    let strawberry : Int = Double.toInt(2.0);
    let tomato : Long = Double.toLong(3.0);

  return;
}

