class A {
    foo(): void{
        let a: long = 60000000000;
        switch(a){
            case 2:
                break;
            case 200:
                break;
            case 200000:
                break;
            case 200000000000:
                break;
            case c'l':
                break;
        }

        let b: Int = 200000;
        const c: int = 210000;
        switch(b){
            case 300000:
                break;
            case c:
                break;
        }
    }
}
