/**
 * Copyright (c) 2025-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http: *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package xgc_ea

const SHARED_OBJECTS_COUNT: testResult, "test20 $2"

/* @@? 17:41 Error Syntax error ESY0224: Identifier expected, got 'string literal'. */
/* @@? 17:41 Error Syntax error ESY0315: Number, string or computed value property name 'test20 $2' is not allowed, use classes to access data by property names that are identifiers */
/* @@? 22:1 Error Syntax error ESY0105: Variable must be initialized or it's type must be declared. */
