/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class A {}
export class B {}
export class C {}
export class D {}
export class E {}
export class F {}
export class G {}
export class H {}
export class I {}
export class J {}
export class K {}
export class L {}
export class M {}
export class N {}
export class O {}
export class P {}
export class Q {}
export class R {}

export default d;

let d = 0;