/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class A {a0 : number[] = []}

function main(){
    let v1 = [number[]]
    let v2 : A = {a0: number[]}
    if(Int[]){}
    while(number[]){}
    let v3 = int[] && true
    let v4 = long[] || false
}

/* @@? 19:15 Error Syntax error ESY0227: Unexpected token 'number'. */
/* @@? 20:23 Error Syntax error ESY0227: Unexpected token 'number'. */
/* @@? 21:8 Error Syntax error ESY0227: Unexpected token 'Int'. */
/* @@? 22:11 Error Syntax error ESY0227: Unexpected token 'number'. */
/* @@? 23:5 Error Syntax error ESY0301: Missing condition in while statement */
/* @@? 23:14 Error Syntax error ESY0227: Unexpected token 'int'. */
/* @@? 24:14 Error Syntax error ESY0227: Unexpected token 'long'. */