/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const v0 = 1516532564n;
const vStr = "Weens"
for (const v2 of vStr) {
    for (let v3 = 0; v3< 93; v3++) {
        const v4 = [-3.0, -921192.1546513135, -1000000.0, 0.21581641635431563, NaN, 1e-15, -1e-15, -28.514616541534];
    }
    const v1 = 545314157;
    const gtTest = v1 > v0;
    const ltTest = v1 < v0;
    const gteTest = v1 >= v0;
    const lteTest = v1 <= v0;
    const eqTest = v1 == v0;
    const neqTest = v1 != v0;
    const addTest = v1 + v0;
    const subTest = v1 - v0;
    const mulTest = v1 * v0;
    const divTest = v1 / v0;
    const modTest = v1 % v0;
    const bitOrTest = v1 | v0;
    const bitAndTest = v1 & v0;
    const bitXorTest = v1 ^ v0;
    const rightTest = v1 >> v0;
    const leftTest = v1 << v0;
}


/* @@? 29:21 Error Semantic error ESE0108: Bad operand type, the types of the operands must be numeric type, enum or String. */
/* @@? 30:21 Error Semantic error ESE0108: Bad operand type, the types of the operands must be numeric type, enum or String. */
/* @@? 31:21 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 32:21 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 33:21 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 34:23 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 35:24 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 36:24 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 37:23 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 38:22 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */