/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class Proxy {
    private foo(target: T) {}
    private bar(
        getter:Method: void {
        const result = getter.getType()
        const Create = new MethodCreate(getter.getName()).addResult(resultType
            Create.AddBody(new AbortController((): Byte => {
                const handle = Reflect.get()
                return (this.foo(handle) as Numeric).toByte.)
            }
        }
    )
}

/* @@? 17:25 Error TypeError: Cannot find type 'T'. */
/* @@? 19:22 Error SyntaxError: Unexpected token, expected ',' or ')'. */
/* @@? 21:28 Error TypeError: Cannot find type 'MethodCreate'. */
/* @@? 22:13 Error SyntaxError: Unexpected token, expected ',' or ')'. */
/* @@? 22:32 Error TypeError: Cannot find type 'AbortController'. */
/* @@? 24:61 Error SyntaxError: Identifier expected, got ')'. */
/* @@? 26:9 Error SyntaxError: Unexpected token, expected ',' or ')'. */
/* @@? 27:5 Error SyntaxError: Unexpected token ')'. */
