/**
 * Copyright (c) 2024-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export declare const byte_1: byte = -127 as byte, byte_2: byte = 126 as byte;
export declare const byte_12: byte = -127 + 1, byte_22: byte = 126 - 1;
export declare const byte_13: byte = Byte.MIN_VALUE, byte_23: byte = 126;
export declare const byte_14: byte = new Byte().toByte()
export declare const int_1: int = 1 + 2 + 3 + 4
const v = 42
export declare const int_12: int = v
export declare const int_15: int
export declare const int_16: int = 12345
export declare const int_17: int = 12345
export declare const int_18: number = 12345
declare const x1: int = 5
declare const x2: int = -5
declare const y1: float = 5.55f
declare const y2: double = -5.55
declare const x3: int = 0x5
declare const x4: int = 0b101
declare const x5: string = "abc"
declare const x6: "abc" = "abc"
declare const x7 = null
declare const x8 = undefined
declare const x11 = 5
declare const x21 = -5
declare const y11 = 5.55
declare const y21 = -5.55
declare const x31 = 0x5
declare const x41 = 0b101
declare const x51 = "abc"
declare const notype

/* @@? 16:37 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_1 */
/* @@? 16:66 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_2 */
/* @@? 17:38 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_12 */
/* @@? 17:64 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_22 */
/* @@? 18:38 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_13 */
/* @@? 18:70 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_23 */
/* @@? 19:38 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: byte_14 */
/* @@? 20:35 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: int_1 */
/* @@? 22:36 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: int_12 */
/* @@? 24:36 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: int_16 */
/* @@? 25:36 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: int_17 */
/* @@? 26:39 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: int_18 */
/* @@? 27:25 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x1 */
/* @@? 28:25 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x2 */
/* @@? 29:27 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: y1 */
/* @@? 30:28 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: y2 */
/* @@? 31:25 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x3 */
/* @@? 32:25 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x4 */
/* @@? 33:28 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x5 */
/* @@? 34:27 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x6 */
/* @@? 35:15 Error Semantic error ESE1111: Missing type annotation for the 'x7'. */
/* @@? 35:20 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x7 */
/* @@? 36:15 Error Semantic error ESE1111: Missing type annotation for the 'x8'. */
/* @@? 36:20 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x8 */
/* @@? 37:15 Error Semantic error ESE1111: Missing type annotation for the 'x11'. */
/* @@? 37:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x11 */
/* @@? 38:15 Error Semantic error ESE1111: Missing type annotation for the 'x21'. */
/* @@? 38:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x21 */
/* @@? 39:15 Error Semantic error ESE1111: Missing type annotation for the 'y11'. */
/* @@? 39:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: y11 */
/* @@? 40:15 Error Semantic error ESE1111: Missing type annotation for the 'y21'. */
/* @@? 40:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: y21 */
/* @@? 41:15 Error Semantic error ESE1111: Missing type annotation for the 'x31'. */
/* @@? 41:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x31 */
/* @@? 42:15 Error Semantic error ESE1111: Missing type annotation for the 'x41'. */
/* @@? 42:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x41 */
/* @@? 43:15 Error Semantic error ESE1111: Missing type annotation for the 'x51'. */
/* @@? 43:21 Error Semantic error ESE125125: Initializers are not allowed in ambient contexts: x51 */
/* @@? 44:15 Error Semantic error ESE1111: Missing type annotation for the 'notype'. */
