/*
 * Copyright (c) 2025-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http: *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

type type_tuple_union = [string, boolean, number] | (this.mnum === other.mnum && this.mden === other.mden
)[]

/* @@? 15:54 Error Syntax error ESY0044: A 'this' type is available only as return type in a non-static method of a class or struct and extension functions. */
/* @@? 15:58 Error Syntax error ESY0228: Unexpected token, expected ')'. */
/* @@? 15:59 Error Semantic error ESE0143: Unresolved reference mnum */
/* @@? 15:68 Error Semantic error ESE0143: Unresolved reference other */
/* @@? 15:82 Error Semantic error ESE0202: 'this' cannot be referenced from a static context */
/* @@? 15:96 Error Semantic error ESE0143: Unresolved reference other */
/* @@? 16:1 Error Syntax error ESY0227: Unexpected token ')'. */
/* @@? 16:1 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 16:3 Error Syntax error ESY0227: Unexpected token ']'. */
/* @@? 28:1 Error Syntax error ESY0228: Unexpected token, expected ']'. */
