/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function main(){ 
    let n1 = 0x8000000000000000;
    let n2 = 9223372036854775808;
    let n3 = 0o1000000000000000000000;
    let n4 = 0b1000000000000000000000000000000000000000000000000000000000000000;

    let n5 = -0x8000000000000001;
    let n6 = -9223372036854775809;
    let n7 = -0o1000000000000000000001;
    let n8 = -0b1000000000000000000000000000000000000000000000000000000000000001;

    let n9 = -0x8000010000000001;
    let n10 = -9223373036854775809;
    let n11 = -0o1000100000000000000001;
    let n12 = -0b1000100000000000000000000000000000000000000000000000000000000001;

    let xint1:int = 0x80000000
    let xint2:int = -0x80000001
}

/* @@? 17:14 Error Syntax error ESY0262: Number is too large. */
/* @@? 17:31 Error Syntax error ESY0227: Unexpected token '0'. */
/* @@? 18:14 Error Syntax error ESY0249: Invalid number. */
/* @@? 19:14 Error Syntax error ESY0262: Number is too large. */
/* @@? 19:37 Error Syntax error ESY0227: Unexpected token '0'. */
/* @@? 20:14 Error Syntax error ESY0262: Number is too large. */
/* @@? 20:79 Error Syntax error ESY0227: Unexpected token '0'. */
/* @@? 22:15 Error Syntax error ESY0262: Number is too large. */
/* @@? 22:32 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 23:15 Error Syntax error ESY0249: Invalid number. */
/* @@? 24:15 Error Syntax error ESY0262: Number is too large. */
/* @@? 24:38 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 25:15 Error Syntax error ESY0262: Number is too large. */
/* @@? 25:80 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 27:15 Error Syntax error ESY0262: Number is too large. */
/* @@? 27:32 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 28:16 Error Syntax error ESY0249: Invalid number. */
/* @@? 29:16 Error Syntax error ESY0262: Number is too large. */
/* @@? 29:39 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 30:16 Error Syntax error ESY0262: Number is too large. */
/* @@? 30:81 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 32:15 Error Semantic error ESE0345: Value is out of range */
/* @@? 32:21 Error Semantic error ESE0318: Type 'Long' cannot be assigned to type 'Int' */
/* @@? 33:15 Error Semantic error ESE0345: Value is out of range */
/* @@? 33:21 Error Semantic error ESE0318: Type 'Long' cannot be assigned to type 'Int' */
