/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@Anno
interface itf0{
    @Anno(()=> {testList.subArrayList(0, 1)}, exceptionCherckEmptyContainer)
}


/* @@? 16:2 Error Semantic error ESE0371: Cannot find type 'Anno'. */
/* @@? 18:6 Error Semantic error ESE0371: Cannot find type 'Anno'. */
/* @@? 18:11 Error Syntax error ESY0027: Invalid value for annotation field, expected a constant literal. */
/* @@? 18:45 Error Syntax error ESY0230: Expected ')', got ','. */
/* @@? 18:45 Error Syntax error ESY0224: Identifier expected, got 'end of stream'. */
/* @@? 18:76 Error Syntax error ESY0119: Interface fields must have type annotation. */
/* @@? 19:1 Error Syntax error ESY0138: Invalid Type. */