/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class D {
  f9(z: W, y: Int): D.f9-2";
}

interface Preferences {
    delenager.Preferences.Core yncCallback): void;
}

/* @@? 16:9 Error Semantic error ESE0308: Circular dependency detected for identifier: D */
/* @@? 17:5 Error Semantic error ESE0017: Only abstract or native methods can't have body. */
/* @@? 17:9 Error Semantic error ESE0371: Cannot find type 'W'. */
/* @@? 17:23 Error Semantic error ESE0070: 'f9' type does not exist. */
/* @@? 17:25 Error Syntax error ESY0227: Unexpected token '-'. */
/* @@? 17:26 Error Syntax error ESY0227: Unexpected token '2'. */
/* @@? 17:27 Error Syntax error ESY0265: Newline is not allowed in strings */
/* @@? 17:27 Error Syntax error ESY0227: Unexpected token ';'. */
/* @@? 19:1 Error Semantic error ESE0308: Circular dependency detected for identifier: Preferences */
/* @@? 20:24 Error Syntax error ESY0224: Identifier expected, got 'end of stream'. */
/* @@? 20:24 Error Syntax error ESY0122: Identifier expected. */
/* @@? 20:24 Error Syntax error ESY0224: Identifier expected, got 'void'. */
/* @@? 20:24 Error Syntax error ESY0228: Unexpected token, expected ','. */
/* @@? 20:24 Error Syntax error ESY0122: Identifier expected. */
/* @@? 20:24 Error Syntax error ESY0228: Unexpected token, expected ','. */
/* @@? 20:24 Error Syntax error ESY0122: Identifier expected. */
/* @@? 20:24 Error Syntax error ESY0224: Identifier expected, got 'end of stream'. */
/* @@? 20:24 Error Syntax error ESY0228: Unexpected token, expected ','. */
/* @@? 20:24 Error Syntax error ESY0122: Identifier expected. */
/* @@? 20:24 Error Syntax error ESY0224: Identifier expected, got 'identification literal'. */
/* @@? 20:24 Error Syntax error ESY0228: Unexpected token, expected ','. */
/* @@? 20:24 Error Syntax error ESY0119: Interface fields must have type annotation. */
/* @@? 20:24 Error Semantic error ESE0070: 'Core' type does not exist. */
