/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const a :number[] = [2];
const s :string= "";
const x: number= 0;
const b = false;
const u = undefined;
const n = null;
const z = s || x || u;
const a1 = a && a;
const a2 = a && s;
const a3 = a && x;
const a4 = a && b;
const a6 = a && u;
const a7 = a && n;
const a8 = a && z;
const s1 = s && a;
const s2 = s && s;
const s3 = s && x;
const s4 = s && b;
const s6 = s && u;
const s7 = s && n;
const s8 = s && z;
const x1 = x && a;
const x2 = x && s;
const x3 = x && x;
const x4 = x && b;
const x6 = x && u;
const x7 = x && n;
const x8 = x && z;
const b1 = b && a;
const b2 = b && s;
const b3 = b && x;
const b4 = b && b;
const b6 = b && u;
const b7 = b && n;
const b8 = b && z;
const u1 = u && a;
const u2 = u && s;
const u3 = u && x;
const u4 = u && b;
const u6 = u && u;
const u7 = u && n;
const u8 = u && z;
const n1 = n && a;
const n2 = n && s;
const n3 = n && x;
const n4 = n && b;
const n6 = n && u;
const n7 = n && n;
const n8 = n && z;
const z1 = z && a;
const z2 = z && s;
const z3 = z && x;
const z4 = z && b;
const z6 = z && u;
const z7 = z && n;
const z8 = z && z;
