/*
 * Copyright (c) 2025-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function main(): void {
    let a = 1, b = 2, c = 3

    a + b = c
    a - b = c
    a * b = c
    a / b = c
    a % b = c
    a ** b = c

    a == b = c
    a != b = c
    a === b = c
    a !== b = c
    a < b = c
    a > b = c
    a <= b = c
    a >= b = c

    a | b = c
    a & b = c
    a ^ b = c

    a << b = c
    a >> b = c
    a >>> b = c

    a && b = c
    a || b = c
    a ?? b = c

    a + b += c
    a + b -= c
    a + b *= c
    a + b /= c
    a + b %= c
    a + b **= c
    a + b &= c
    a + b |= c
    a + b ^= c
    a + b <<= c
    a + b >>= c
    a + b >>>= c

    a + b + c = c
    a | b ^ c = c
}
/* @@? 19:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 19:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 20:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 20:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 21:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 21:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 22:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 22:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 23:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 23:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 24:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 24:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 26:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 26:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 27:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 27:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 28:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 28:13 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 29:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 29:13 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 30:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 30:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 31:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 31:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 32:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 32:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 33:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 33:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 35:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 35:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 36:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 36:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 37:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 37:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 39:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 39:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 40:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 40:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 41:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 41:13 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 43:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 43:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 44:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 44:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 45:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 45:5 Error Warning W971874: result of the nullish-coalescing expression is equal to its left-hand-side expression value. */
/* @@? 45:12 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 47:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 47:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 48:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 48:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 49:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 49:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 50:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 50:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 51:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 51:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 52:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 52:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 53:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 53:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 54:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 54:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 55:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 55:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 56:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 56:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 57:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 57:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 58:5 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 58:11 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 60:9 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 60:15 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 61:9 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 61:15 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
