/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

{% for
  const enum Direction {
   __empty = 1,
  }

/* @@? 16:2 Error Syntax error ESY0227: Unexpected token '%'. */
/* @@? 16:4 Error Syntax error ESY0227: Unexpected token 'for'. */
/* @@? 17:3 Error Syntax error ESY0230: Expected '(', got 'const'. */
/* @@? 32:1 Error Syntax error ESY0211: Invalid left-hand side in 'for' statement: must have a single binding. */
/* @@? 32:1 Error Syntax error ESY0230: Expected ';', got 'end of stream'. */
/* @@? 32:1 Error Syntax error ESY0227: Unexpected token 'end of stream'. */
/* @@? 32:1 Error Syntax error ESY0228: Unexpected token, expected ';'. */
/* @@? 32:1 Error Syntax error ESY0227: Unexpected token 'end of stream'. */
/* @@? 32:1 Error Syntax error ESY0230: Expected ')', got 'end of stream'. */
/* @@? 32:1 Error Syntax error ESY0227: Unexpected token 'end of stream'. */
/* @@? 32:1 Error Syntax error ESY0230: Expected '}', got 'end of stream'. */
