/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http: *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class Arr<T> {
	public mp<U>(a: int): FixedArray<()> 
}

/* @@? 16:11 Error Semantic error ESE0017: Only abstract or native methods can't have body. */
/* @@? 16:24 Error Semantic error ESE0277: FixedArray<T> must have only one type parameter. */
/* @@? 16:37 Error Syntax error ESY0228: Unexpected token, expected '=>'. */
/* @@? 16:37 Error Syntax error ESY0228: Unexpected token, expected '>'. */
/* @@? 16:37 Error Syntax error ESY0227: Unexpected token '>'. */