/**
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let s: string = "123"
let i: number = 0

let bad = 'c' + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i] + s[i]

/* @@? 19:17 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:19 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:19 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:24 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:26 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:26 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:31 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:33 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:33 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:38 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:40 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:40 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:45 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:47 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:47 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:52 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:54 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:54 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:59 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:61 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:61 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:66 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:68 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:68 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:73 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:75 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:75 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:80 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:82 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:82 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:87 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:89 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:89 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:94 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:96 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:96 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:101 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:103 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:103 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:108 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:110 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:110 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:115 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:117 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:117 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:122 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:124 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:124 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:129 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:131 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:131 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:136 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:138 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:138 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:143 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:145 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:145 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:150 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:152 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:152 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:157 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:159 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:159 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:164 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:166 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:166 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:171 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:173 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:173 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:178 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:180 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:180 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:185 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:187 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:187 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:192 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:194 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:194 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:199 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:201 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:201 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:206 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:208 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:208 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:213 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:215 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:215 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:220 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:222 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:222 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:227 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:229 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:229 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:234 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:236 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:236 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:241 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:243 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:243 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:248 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:250 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:250 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:255 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:257 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:257 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:262 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:264 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:264 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:269 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:271 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:271 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:276 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:278 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:278 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:283 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:285 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:285 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:290 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:292 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:292 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:297 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:299 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:299 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:304 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:306 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:306 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:311 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:313 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:313 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:318 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:320 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:320 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:325 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:327 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:327 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:332 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:334 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:334 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:339 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:341 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:341 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:346 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:348 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:348 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:353 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:355 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:355 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:360 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:362 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:362 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:367 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:369 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:369 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:374 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:376 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:376 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:381 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:383 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:383 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:388 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:390 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:390 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:395 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:397 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:397 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:402 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:404 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:404 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:409 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:411 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:411 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:416 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:418 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:418 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:423 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:425 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:425 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:430 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:432 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:432 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:437 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:439 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:439 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:444 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:446 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:446 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:451 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:453 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:453 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:458 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:460 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:460 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:465 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:467 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:467 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:472 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:474 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:474 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:479 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:481 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:481 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:486 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:488 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:488 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:493 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:495 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:495 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:500 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:502 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:502 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:507 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:509 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:509 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:514 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:516 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:516 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:521 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:523 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:523 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:528 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:530 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:530 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:535 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:537 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:537 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:542 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:544 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:544 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:549 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:551 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:551 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:556 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:558 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:558 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:563 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:565 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:565 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:570 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:572 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:572 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:577 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:579 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:579 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
/* @@? 19:584 Error Semantic error ESE0127: No matching indexing signature for $_get(Double) */
/* @@? 19:586 Error Semantic error ESE0251: Cannot find index access method with the required signature. */
/* @@? 19:586 Error Semantic error ESE0046: Type 'Double' is not compatible with type 'Int' at index 1 */
