/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

enum Color { Red = 700, Green = 500, Blue = 400 }

const test_const_1: Color
const test_const_2: Number
const test_const_3: String

function main() {
  const test_const_4: Number
  const test_const_5: Color
  const test_const_6: String

  let values: number[] = [];
  for (const test_const_7 of values) {}
}


/* @@? 18:7 Error Semantic error ESE0363: Missing initializer in const declaration */
/* @@? 19:7 Error Semantic error ESE0363: Missing initializer in const declaration */
/* @@? 20:7 Error Semantic error ESE0363: Missing initializer in const declaration */
/* @@? 23:9 Error Semantic error ESE0363: Missing initializer in const declaration */
/* @@? 24:9 Error Semantic error ESE0363: Missing initializer in const declaration */
/* @@? 25:9 Error Semantic error ESE0363: Missing initializer in const declaration */