/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

do export  Boolean [1] = delete
   while(true)


/* @@? 16:4 Error Syntax error ESY0227: Unexpected token 'export'. */
/* @@? 16:4 Error Syntax error ESY0300: Missing body in do while statement */
/* @@? 16:4 Error Syntax error ESY0228: Unexpected token, expected 'while'. */
/* @@? 16:12 Error Syntax error ESY0228: Unexpected token, expected '('. */
/* @@? 16:20 Error Syntax error ESY0204: Invalid left-hand side in array destructuring pattern. */
/* @@? 16:26 Error Syntax error ESY0049: Invalid destructuring assignment target. */
/* @@? 16:26 Error Semantic error ESE55815: Types cannot be modified at runtime with 'delete'. */
/* @@? 17:4 Error Syntax error ESY0230: Expected ')', got 'while'. */
/* @@? 29:1 Error Syntax error ESY0227: Unexpected token 'end of stream'. */
