/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

do a 


/* @@? 16:4 Error Semantic error ESE0143: Unresolved reference a */
/* @@? 24:79 Error Syntax error ESY0228: Unexpected token, expected 'while'. */
/* @@? 24:79 Error Syntax error ESY0228: Unexpected token, expected '('. */
/* @@? 24:79 Error Syntax error ESY0227: Unexpected token 'end of stream'. */
/* @@? 24:79 Error Syntax error ESY0301: Missing condition in do while statement */
/* @@? 24:79 Error Syntax error ESY0230: Expected ')', got 'end of stream'. */