/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as Pt from "mod" /* @@ label1 */assert /* @@ label2 */{ type: /* @@ label3 */"json" }


/* @@@ label1 Error SyntaxError: Import assertion is not supported, please use the ordinary import syntax instead! */
/* @@@ label1 Error TypeError: Unresolved reference assert */
/* @@@ label2 Error SyntaxError: Unexpected token '{'. */
/* @@@ label3 Error SyntaxError: Label must be followed by a loop statement. */
