/*
 * Copyright (c) 2024-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
class URIError extends /* @@ label */WebAssembly /* @@ label1 */{
  WebAssembly : WeakMap [-6]
}

/* @@@ label Error Semantic error ESE0371: Cannot find type 'WebAssembly'. */
/* @@@ label Error Semantic error ESE0176: The super type of 'URIError' class is not extensible. */
/* @@@ label1 Error Semantic error ESE0349: Class 'URIError' is already defined. */
/* @@? 17:26 Error Syntax error ESY0228: Unexpected token, expected ']'. */
/* @@? 17:26 Error Syntax error ESY0227: Unexpected token ']'. */
/* @@? 17:27 Error Syntax error ESY0227: Unexpected token '6'. */
/* @@? 17:28 Error Syntax error ESY0227: Unexpected token ']'. */
