/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class Menu{}

class MenuProvider{
   menuList?: Menu[];
}

class View {
   menu: Menu[]
   constructor(mp: MenuProvider) {
      let tm: Menu[] = mp.menuList == undefined ? [] : mp.menuList!;
      this.menu = mp.menuList == undefined ? [] : mp.menuList!;
   }
}

