/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface"actual : " + actual.result[i]


/* @@? 16:10 Error Syntax error ESY0315: Number, string or computed value property name 'actual : ' is not allowed, use classes to access data by property names that are identifiers */
/* @@? 16:10 Error Syntax error ESY0224: Identifier expected, got 'string literal'. */
/* @@? 16:22 Error Syntax error ESY0228: Unexpected token, expected '{'. */
/* @@? 16:30 Error Syntax error ESY0119: Interface fields must have type annotation. */
/* @@? 16:38 Error Syntax error ESY0228: Unexpected token, expected ']'. */
/* @@? 16:38 Error Syntax error ESY0228: Unexpected token, expected ','. */
/* @@? 16:38 Error Syntax error ESY0224: Identifier expected, got 'identification literal'. */
/* @@? 16:39 Error Syntax error ESY0122: Identifier expected. */
/* @@? 16:39 Error Syntax error ESY0228: Unexpected token, expected ','. */
/* @@? 16:39 Error Syntax error ESY0224: Identifier expected, got 'end of stream'. */
/* @@? 30:76 Error Syntax error ESY0122: Identifier expected. */
/* @@? 30:76 Error Syntax error ESY0228: Unexpected token, expected '}'. */