/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

switch:[11](q): [12]{: [13]case: [14]1:: [15]{: [16]q: [17] +=: [18]2;: 
[38]try: [39]{: [40]s: [41] +=: [42]"cba";: [43]q: [44] +=: [45]5;: [46]throw: [98]

/* @@? 16:7 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:7 Error Syntax error ESY0230: Expected '(', got ':'. */
/* @@? 16:7 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 16:15 Error Syntax error ESY0231: Unexpected token ':', expected 'case' or 'default'. */
/* @@? 16:15 Error Syntax error ESY0230: Expected ')', got ':'. */
/* @@? 16:15 Error Syntax error ESY0230: Expected '{', got ':'. */
/* @@? 16:21 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 16:22 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:22 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 16:28 Error Syntax error ESY0227: Unexpected token 'case'. */
/* @@? 16:32 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:32 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 16:38 Error Syntax error ESY0227: Unexpected token '1'. */
/* @@? 16:39 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:40 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:40 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 16:46 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 16:47 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:47 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 16:53 Error Syntax error ESY0227: Unexpected token 'q'. */
/* @@? 16:56 Error Syntax error ESY0038: Label must be followed by a loop statement. */
/* @@? 16:56 Error Semantic error ESE0025: Invalid left-hand side of assignment expression */
/* @@? 16:61 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 16:63 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:69 Error Syntax error ESY0227: Unexpected token '2'. */
/* @@? 16:71 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 16:71 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 17:5 Error Syntax error ESY0227: Unexpected token 'try'. */
/* @@? 17:5 Error Syntax error ESY0039: A try statement should contain either finally clause or at least one catch clause. */
/* @@? 17:8 Error Syntax error ESY0230: Expected '{', got ':'. */
/* @@? 17:8 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 17:14 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 17:15 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 17:21 Error Syntax error ESY0227: Unexpected token 's'. */
/* @@? 17:24 Error Syntax error ESY0038: Label must be followed by a loop statement. */
/* @@? 17:29 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 17:31 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 17:37 Error Syntax error ESY0227: Unexpected token 'cba'. */
/* @@? 17:43 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 17:49 Error Syntax error ESY0227: Unexpected token 'q'. */
/* @@? 17:52 Error Syntax error ESY0038: Label must be followed by a loop statement. */
/* @@? 17:57 Error Syntax error ESY0072: Invalid left-hand side in assignment expression. */
/* @@? 17:59 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 17:65 Error Syntax error ESY0227: Unexpected token '5'. */
/* @@? 17:67 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 17:73 Error Syntax error ESY0227: Unexpected token 'throw'. */
/* @@? 17:78 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 67:1 Error Syntax error ESY0230: Expected '}', got 'end of stream'. */
