/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class MathSpectralNorm {

  private static spectralnorm(n: int): double {
    for await (i = 0; i < n : i++) {
      vbv += u[i] * v[i];
      vv  += v[i] * v[i];

    }
    return sqrt(vbv / vv);
  }
}


/* @@? 19:16 Error Semantic error ESE0143: Unresolved reference i */
/* @@? 19:18 Error Syntax error ESY0227: Unexpected token '='. */
/* @@? 19:29 Error Syntax error ESY0230: Expected ';', got ':'. */
/* @@? 19:29 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 19:31 Error Syntax error ESY0230: Expected ')', got 'identification literal'. */
/* @@? 19:34 Error Syntax error ESY0227: Unexpected token ')'. */
/* @@? 19:36 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 20:7 Error Semantic error ESE0143: Unresolved reference vbv */
/* @@? 20:14 Error Semantic error ESE0143: Unresolved reference u */
/* @@? 20:14 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 20:21 Error Semantic error ESE0143: Unresolved reference v */
/* @@? 20:21 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 21:7 Error Semantic error ESE0143: Unresolved reference vv */
/* @@? 21:14 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */
/* @@? 21:21 Error Semantic error ESE0252: Indexed access is not supported for such expression type. */