/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class A {}
class B extendsA {}

functioew Nu
nt = 10 A {}

functioew Nu
nt = 10
)void {nt = 20, g: s A {}
int = 10
) => B = (p:+): A6=> { reƒurn _ew B(ô }
|ó


/* @@? 17:9 Error Syntax error ESY0230: Expected '{', got 'identification literal'. */
/* @@? 17:18 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 19:1 Error Semantic error ESE0143: Unresolved reference functioew */
/* @@? 19:11 Error Syntax error ESY0227: Unexpected token 'Nu'. */
/* @@? 19:11 Error Semantic error ESE0143: Unresolved reference Nu */
/* @@? 20:1 Error Syntax error ESY0112: Unexpected token, expected an identifier. */
/* @@? 20:1 Error Semantic error ESE0143: Unresolved reference nt */
/* @@? 20:10 Error Syntax error ESY0318: Class cannot be used as object. */
/* @@? 20:10 Error Syntax error ESY0227: Unexpected token 'A'. */
/* @@? 20:12 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 22:11 Error Syntax error ESY0227: Unexpected token 'Nu'. */
/* @@? 23:1 Error Syntax error ESY0112: Unexpected token, expected an identifier. */
/* @@? 24:1 Error Syntax error ESY0227: Unexpected token ')'. */
/* @@? 24:2 Error Syntax error ESY0227: Unexpected token 'void'. */
/* @@? 24:7 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 24:8 Error Syntax error ESY0112: Unexpected token, expected an identifier. */
/* @@? 24:8 Error Semantic error ESE0143: Unresolved reference nt */
/* @@? 24:16 Error Syntax error ESY0227: Unexpected token ','. */
/* @@? 24:18 Error Syntax error ESY0227: Unexpected token 'g'. */
/* @@? 24:21 Error Syntax error ESY0038: Label must be followed by a loop statement. */
/* @@? 24:21 Error Semantic error ESE0143: Unresolved reference s */
/* @@? 24:23 Error Syntax error ESY0227: Unexpected token 'A'. */
/* @@? 24:23 Error Syntax error ESY0318: Class cannot be used as object. */
/* @@? 24:25 Error Syntax error ESY0227: Unexpected token '{'. */
/* @@? 25:1 Error Syntax error ESY0227: Unexpected token 'int'. */
/* @@? 26:1 Error Syntax error ESY0227: Unexpected token ')'. */
/* @@? 26:3 Error Syntax error ESY0227: Unexpected token '=>'. */
/* @@? 26:13 Error Syntax error ESY0112: Unexpected token, expected an identifier. */
/* @@? 26:13 Error Semantic error ESE0371: Cannot find type ''. */
/* @@? 26:14 Error Syntax error ESY0229: Unexpected token, expected ',' or ')'. */
/* @@? 26:14 Error Syntax error ESY0230: Expected '=>', got '+'. */
/* @@? 26:15 Error Syntax error ESY0227: Unexpected token ')'. */
/* @@? 26:16 Error Syntax error ESY0227: Unexpected token ':'. */
/* @@? 26:18 Error Syntax error ESY0227: Unexpected token 'A6'. */
/* @@? 26:18 Error Semantic error ESE0107: Bad operand type, the types of the operands must be numeric type. */
/* @@? 26:18 Error Semantic error ESE0132: The type of parameter 'A6' cannot be inferred */
/* @@? 26:25 Error Semantic error ESE0143: Unresolved reference reƒurn */
/* @@? 26:32 Error Syntax error ESY0227: Unexpected token '_ew'. */
/* @@? 26:32 Error Semantic error ESE0143: Unresolved reference _ew */
/* @@? 26:36 Error Syntax error ESY0227: Unexpected token 'B'. */
/* @@? 26:36 Error Semantic error ESE0172: No static $_invoke method and static $_instantiate method in B. B() is not allowed. */
/* @@? 26:40 Error Syntax error ESY0229: Unexpected token, expected ',' or ')'. */
/* @@? 27:2 Error Semantic error ESE0143: Unresolved reference ó */
/* @@? 73:79 Error Syntax error ESY0230: Expected '}', got 'end of stream'. */