/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

async WeakMap => ...delete const { Intl } = [ { opt } = [({} ? 4 : Array[-=])];
, ... || new ({.: 0}[])(,{: 88}["-1"]), ...opt, (7 ?  : null)][true[( ? 5 : {}.arity.E)]];
 >>>= sub(await delete await ArrayBuffer ^= await delete )<missing '
'> __a:be
}


/* @@? 16:7 Error SyntaxError: 'async' flags must be used for functions only at top-level. */
/* @@? 16:15 Error SyntaxError: Unexpected token, expected an identifier. */
/* @@? 16:15 Error SyntaxError: Unexpected token, expected '('. */
/* @@? 16:28 Error SyntaxError: Parameter declaration should have an explicit type annotation. */
/* @@? 16:28 Error SyntaxError: Rest parameter must be the last formal parameter. */
/* @@? 16:36 Error SyntaxError: Namespace cannot be used as object. */
/* @@? 16:43 Error SyntaxError: Unexpected token '='. */
/* @@? 16:43 Error TypeError: Indexed access is not supported for such expression type. */
/* @@? 16:74 Error SyntaxError: Unexpected token '-='. */
/* @@? 16:79 Error SyntaxError: Unexpected token, expected ']'. */
/* @@? 17:1 Error SyntaxError: Unexpected token ','. */
/* @@? 17:3 Error SyntaxError: Unexpected token '...'. */
/* @@? 17:15 Error SyntaxError: Using object literals to declare types in place is not supported. Please declare types and interfaces explicitly! */
/* @@? 17:16 Error SyntaxError: Unexpected token '.'. */
/* @@? 17:17 Error SyntaxError: Unexpected token ':'. */
/* @@? 17:19 Error SyntaxError: Unexpected token '0'. */
/* @@? 17:21 Error SyntaxError: Unexpected token, expected ')'. */
/* @@? 17:22 Error SyntaxError: Unexpected token ']'. */
/* @@? 17:23 Error SyntaxError: Unexpected token ')'. */
/* @@? 17:23 Error TypeError: This expression is not callable. */
/* @@? 17:23 Error TypeError: Indexed access is not supported for such expression type. */
/* @@? 17:25 Error SyntaxError: Unexpected token ','. */
/* @@? 17:26 Error SyntaxError: Unexpected token, expected ',' or ')'. */
/* @@? 17:27 Error SyntaxError: Unexpected token ':'. */
/* @@? 17:29 Error SyntaxError: Unexpected token '88'. */
/* @@? 17:38 Error SyntaxError: Unexpected token ')'. */
/* @@? 17:39 Error SyntaxError: Unexpected token ','. */
/* @@? 17:41 Error SyntaxError: Unexpected token '...'. */
/* @@? 17:44 Error SyntaxError: Unexpected token 'opt'. */
/* @@? 17:44 Error TypeError: Unresolved reference opt */
/* @@? 17:47 Error SyntaxError: Unexpected token ','. */
/* @@? 17:47 Error TypeError: This expression is not callable. */
/* @@? 17:55 Error SyntaxError: Unexpected token ':'. */
/* @@? 17:57 Error SyntaxError: Unexpected token. */
/* @@? 17:62 Error SyntaxError: Unexpected token ']'. */
/* @@? 17:62 Error TypeError: Indexed access is not supported for such expression type. */
/* @@? 17:71 Error SyntaxError: Unexpected token '?'. */
/* @@? 17:73 Error SyntaxError: Unexpected token, expected ')'. */
/* @@? 17:75 Error SyntaxError: Unexpected token, expected ']'. */
/* @@? 17:77 Error SyntaxError: Unexpected token, expected ']'. */
/* @@? 17:78 Error SyntaxError: Unexpected token '}'. */
/* @@? 17:87 Error SyntaxError: Unexpected token ')'. */
/* @@? 17:88 Error SyntaxError: Unexpected token ']'. */
/* @@? 17:89 Error SyntaxError: Unexpected token ']'. */
/* @@? 18:2 Error SyntaxError: Unexpected token '>>>='. */
/* @@? 18:7 Error SyntaxError: Unexpected token 'sub'. */
/* @@? 18:7 Error TypeError: Unresolved reference sub */
/* @@? 18:24 Error SyntaxError: Unexpected token 'await'. */
/* @@? 18:24 Error SyntaxError: Unexpected token, expected ',' or ')'. */
/* @@? 18:24 Error TypeError: Invalid left-hand side of assignment expression */
/* @@? 18:30 Error SyntaxError: Class cannot be used as object. */
/* @@? 18:30 Error TypeError: 'await' expressions require Promise object as argument. */
/* @@? 18:42 Error SyntaxError: Invalid left-hand side in assignment expression. */
/* @@? 18:58 Error SyntaxError: Unexpected token ')'. */
/* @@? 18:60 Error TypeError: Unresolved reference missing */
/* @@? 18:68 Error SyntaxError: Unexpected token ''. */
/* @@? 18:68 Error SyntaxError: Newline is not allowed in strings */
/* @@? 18:69 Error SyntaxError: Unexpected token '}'. */
/* @@? 18:69 Error SyntaxError: Unexpected token '> __a:be'. */
/* @@? 18:69 Error SyntaxError: Newline is not allowed in strings */
