/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

async WeakMap => ...delete const { }


/* @@? 16:7 Error Syntax error ESY0202: 'async' flags must be used for functions only at top-level. */
/* @@? 16:15 Error Syntax error ESY0112: Unexpected token, expected an identifier. */
/* @@? 16:15 Error Syntax error ESY0228: Unexpected token, expected '('. */
/* @@? 16:28 Error Syntax error ESY0194: Parameter declaration should have an explicit type annotation. */
/* @@? 16:28 Error Syntax error ESY0067: Rest parameter must be the last formal parameter. */