/**
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Metadata;

table Decls {
    imports:[ImportDecl];
    re_exports:[ReExportDecl];
    local_exports:[LocalExportDecl];
    classes:[ClassDecl];
    interfaces:[InterfaceDecl];
    annotations:[AnnotationDecl];
    types:[TypeDecl];
    package_name:string;
}

// Common entities

union RefType {
    class:ClassDecl,
    interface:InterfaceDecl,
    annotation:AnnotationDecl,
    type:TypeDecl,
    typeParam:TypeParamDecl
}

union Type {
    Builtin:BuiltinType,
    Array:ArrayType,
    Ref:TypeRef,
    Function:FunctionType,
    Tuple:TupleType,
    Union:UnionType,
    StringLiteral:StringLiteralType,
    Partial:PartialType,
    This:ThisType
}

// Class-like declarations

table ImportDecl {
    from:string (required);
    module_name:string (required);
    decl_names:[string];
}

enum ReExportKind : byte {
    Star,
    Named,
    Namespace
}

table ReExportDecl {
    from:string (required);
    module_name:string (required);
    kind:ReExportKind;
    exported_name:string;
    imported_name:string;
    is_type:bool;
}

table LocalExportDecl {
    exported_name:string (required);
    local_name:string (required);
    is_type:bool;
}

enum EnumKind : byte {
    NONE = 0,
    NUMERIC = 1,
    STRING = 2
}

table ClassDecl {
    name:string (required);
    is_namespace:bool;
    is_builtin:bool;
    enum_kind:EnumKind;
    enum_values:[string];
    enum_underlying_type:Type;
    methods:[FunctionDecl];
    properties:[PropertyDecl];
    decls:Decls;
    type_params:[TypeParamDecl];
    extended_class:Type;
    implemented_interfaces:[Type];
    is_final:bool;
    is_abstract:bool;
    internal_name:string;
}

table InterfaceDecl {
    name:string (required);
    is_builtin:bool;
    methods:[FunctionDecl];
    type_params:[TypeParamDecl];
    implemented_interfaces:[Type];
    properties:[PropertyDecl];
    internal_name:string;
}

table AnnotationDecl {
    name:string (required);
    internal_name:string (required);
    properties:[PropertyDecl];
    access_restriction_modules:[string];
    access_restriction_annotation_name:string;
}

table TypeDecl {
    name:string (required);
    type:Type (required);
    type_params:[TypeParamDecl];
}

// Callable declarations

table FunctionDecl {
    name:string (required);
    return_type:Type;
    is_static:bool;
    value_params:[ValueParamDecl];
    type_params:[TypeParamDecl];
    overloads:[FunctionDecl];
    is_protected:bool;
    is_getter:bool;
    is_setter:bool;
    overload_group:string;
    overload_group_index:int32;
    is_final:bool;
    is_native:bool;
    is_abstract:bool;
}

table PropertyDecl {
    name:string (required);
    return_type:Type (required);
    is_static:bool;
    is_const:bool;
    is_protected:bool;
    is_readonly:bool;
}

// Parameter declarations

table ValueParamDecl {
    name:string (required);
    type:Type (required);
    is_readonly:bool;
    is_optional:bool;
    is_rest:bool;
}

enum TypeParamVariance : byte {
    INV = 0,
    IN = 1,
    OUT = 2
}

table TypeParamDecl {
    name:string (required);
    variance:TypeParamVariance;
    constraint:Type;
    default_type:Type;
}

// Types

enum BuiltinTypeKind : byte {
    byte_ = 0,
    short_ = 1,
    int_ = 2,
    long_ = 3,
    float_ = 4,
    double_ = 5,
    number = 6,
    boolean = 7,
    char = 8,
    string_ = 9,
    bigint = 10,
    any = 11,
    object = 12,
    never = 13,
    void = 14,
    undefined = 15,
    null = 16,
}

table BuiltinType {
    kind:BuiltinTypeKind;
}

table ArrayType {
    element_type:Type;
    is_readonly: bool;
    is_value_array: bool;
}

table TypeRef {
    fqname:string (required);
    type_args:[Type];
    allow_unsafe_variance:bool;
}

table FunctionTypeParam {
    name:string;
    type:Type (required);
    is_optional:bool;
    is_rest:bool;
}

table FunctionType {
    params:[FunctionTypeParam];
    return_type:Type (required);
    has_receiver:bool;
}

table TupleType {
    elements:[Type];
}

table UnionType {
    components:[Type] (required);
}

table StringLiteralType {
    value:string (required);
}

table PartialType {
    inner_type:Type (required);
}

table ThisType {
}


root_type Decls;
