export class MyClass {
    x: number = 11
/**
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


    hehehe(): void {
        console.log("aaa");
    }

    hohoho(): null {
        return null;
    }

    hahaha(): undefined {
        return undefined
    }

    foo(): Any {
        return undefined
    }

    fee(error: string): never {
        throw new Error(error);
    }

    faa(): string {
        return "faa"
    }

    lol(): bigint {
        return 1n
    }

    lel(): Object {
        let x: Object = new Object();
        if (true) {
            x = 10
        }
        return x
    }
}
