/**
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class MyClass {
    x: number = 11

    hehehe(): int {
        return 1;
    }

    hohoho(): long {
        return 1 as long;
    }

    hahaha(): double {
        return 1.0
    }

    foo(): boolean {
        return false;
    }

    fee(): byte {
        return 1 as byte;
    }

    faa(): short {
        return 1 as short
    }

    lol(): char {
        return c'a'
    }

    lel(): float {
        return 1.0f
    }
}
